/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BlockContainer: typeof import('./src/components/layouts/BlockContainer.vue')['default']
    Boost: typeof import('./src/components/boost/boost.vue')['default']
    Button: typeof import('./src/components/button/button.vue')['default']
    Column: typeof import('./src/components/layouts/Column.vue')['default']
    FirstSlide: typeof import('./src/components/preview/firstSlide.vue')['default']
    Footer: typeof import('./src/components/top/footer.vue')['default']
    FourthSlide: typeof import('./src/components/preview/fourthSlide.vue')['default']
    FullPage: typeof import('./src/components/layouts/FullPage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Name: typeof import('./src/components/squad/name.vue')['default']
    Page: typeof import('./src/components/layouts/Page.vue')['default']
    Referral: typeof import('./src/components/referral/referral.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondSlide: typeof import('./src/components/preview/secondSlide.vue')['default']
    ServiceWorks: typeof import('./src/components/utilityScreens/ServiceWorks.vue')['default']
    SocketFrame: typeof import('./src/components/main/socketFrame.vue')['default']
    SocketFrameNewVersion: typeof import('./src/components/main/socketFrameNewVersion.vue')['default']
    Squad: typeof import('./src/components/squad/squad.vue')['default']
    SquadCreate: typeof import('./src/components/squad/squadCreate.vue')['default']
    SquadTable: typeof import('./src/components/squad/SquadTable.vue')['default']
    Table: typeof import('./src/components/top/table.vue')['default']
    ThirdSlide: typeof import('./src/components/preview/thirdSlide.vue')['default']
    Title: typeof import('./src/components/layouts/Title.vue')['default']
    Top: typeof import('./src/components/top/top.vue')['default']
    TopByLeague: typeof import('./src/components/top/topByLeague.vue')['default']
    TwoColumns: typeof import('./src/components/layouts/TwoColumns.vue')['default']
    UserInfoCard: typeof import('./src/components/main/userInfoCard.vue')['default']
  }
}
